{% set name = "kit4dl" %}
{% set version = "2023.11b1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kit4dl-{{ version }}.tar.gz
  sha256: 75d680a402b30cb3d001c83dddf20ee67a6bd7b066a1ab90f28e2dbbcfdb120c


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kit4dl = kit4dl.cli.app:run

requirements:
  host:
    - python >=3.10,<3.12
    - pip
  run:
    - python >=3.10,<3.12
    - pytorch >=1.11.0,<2.1.0
    - lightning <=2.1.0.rc0
    - torchmetrics >=0.7.0,<1.1.0
    - numpy >=1.17.2,<=1.25.3
    - pydantic >=2.0.0,<2.2.0
    - scikit-learn >=1.2.0
    - colormath
    - tqdm >=4.57.0,<4.67.0
    - colorama >=0.4.3,<0.5.0
    - shellingham >=1.3.0,<2.0.0
    - rich >=10.11.0,<14.0.0
    - typing-extensions >=4.0.0,<4.8.0
    - Jinja2 <3.2.0
    - typer
    - toml

test:
  imports:
    - kit4dl
  commands:
    - pip check
    - kit4dl --help
  requires:
    - pip

about:
  home: https://github.com/opengeokube/kit4dl/
  license: MIT
  license_file: LICENSE
  summary: 'A quick way to start with machine and deep learning'
  dev_url: https://github.com/opengeokube/kit4dl
  doc_url: https://pypi.org/project/kit4dl/
  doc_source_url: https://github.com/opengeokube/kit4dl/blob/main/README.md

extra:
  recipe-maintainers:
    - jamesWalczak
