{% set python_min = '3.10' %}
{% set name = "kit4dl" %}
{% set version = "2024.5b2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kit4dl-{{ version }}.tar.gz
  sha256: 561460352670649ed1b21e2afb1cb53467198ef12d4380201eec36c5f1633790

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kit4dl = kit4dl.cli.app:run

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<3.12
    - pytorch >=2.1.0
    - lightning >=2.2.4
    - torchmetrics >=1.1.0
    - numpy >=1.17.2,<=1.25.3
    - pydantic >2.4.0
    - scikit-learn
    - colormath
    - tqdm >=4.57.0,<4.67.0
    - colorama >=0.4.3,<0.5.0
    - shellingham >=1.3.0,<2.0.0
    - rich >=10.11.0,<14.0.0
    - typing-extensions >=4.8.0
    - Jinja2 <3.2.0
    - typer
    - toml

test:
  imports:
    - kit4dl
  commands:
    - pip check
    - kit4dl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeokube/kit4dl/
  license: MIT
  license_file: LICENSE
  summary: 'A quick way to start with machine and deep learning'
  dev_url: https://github.com/opengeokube/kit4dl
  doc_url: https://opengeokube.github.io/kit4dl/
  doc_source_url: https://github.com/opengeokube/kit4dl/blob/main/README.md

extra:
  recipe-maintainers:
    - jamesWalczak
