{% set name = "kit4dl" %}
{% set version = "2023.9b0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kit4dl-{{ version }}.tar.gz
  sha256: 7ff04d77a36ed26ea259439dd3a22540304783ec74c1f829f9d2dda70ffe3f39

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kit4dl = kit4dl.cli.app:run

requirements:
  host:
    - python >=3.10
    - pip    
  run:
    - python >=3.10
    - pytorch
    - lightning
    - torchmetrics
    - numpy <=1.25.0
    - pydantic <2.0.0
    - scikit-learn >=1.2.0
    - colormath
    - tqdm
    - colorama >=0.4.3,<0.5.0
    - shellingham >=1.3.0,<2.0.0
    - rich >=10.11.0,<14.0.0
    - typer
    - toml

test:
  imports:
    - kit4dl
  commands:
    - pip check
    - kit4dl --help
  requires:
    - pip

about:
  home:  https://github.com/opengeokube/kit4dl/
  license: MIT
  license_file: LICENSE
  summary: 'A quick way to start with machine and deep learning'
  dev_url: https://github.com/opengeokube/kit4dl
  doc_url: https://pypi.org/project/kit4dl/
  doc_source_url: https://github.com/opengeokube/kit4dl/blob/main/README.md

extra:
  recipe-maintainers:
      - jamesWalczak
